services:
  veeam-designer:
    build: .
    image: emb079/veeam-designer:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./profiles.json:/app/profiles.json:ro
